openapi: 3.0.4
info:
  title: Gold Price
  description: Gold Price is a simple tool for getting the current price of gold. It returns the current price of gold in any currency and in various units.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/goldprice:
    get:
      summary: Get Current Gold Price
      description: Gold Price is a simple tool for getting the current price of gold. It returns the current price of gold in any currency and in various units.
      operationId: goldprice
      parameters:
      - name: currency
        default: USD
        in: query
        schema:
          type: string
        required: false
        description: The currency to get the price in (USD, EUR, GBP, etc.)
        example: USD
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  currency: USD
                  gram: 103.71
                  kilogram: 103705.56
                  ounce: 2940
                  lastUpdated: 1740074702
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
